<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { booksApi, pagesApi } from '@/services/api'
import type { BookPageRecord, BookRecord } from '@/types/models'
import Badge from '@/components/ui/Badge.vue'
const props = defineProps<{ id: string }>(); const book = ref<BookRecord | null>(null); const pages = ref<BookPageRecord[]>([]); const error = ref('')
onMounted(async () => { try { book.value = await booksApi.detail(props.id); pages.value = await pagesApi.list(props.id) } catch (err) { error.value = err instanceof Error ? err.message : '加载失败' } })
</script>
<template><section><div class="page-header"><div><p class="text-xs font-extrabold uppercase tracking-widest text-[#705c21]">Book Info</p><h1 class="text-3xl font-extrabold text-[#142217]">书籍信息</h1></div></div><p v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{{ error }}</p><article v-if="book" class="page-card space-y-4"><div class="flex items-start justify-between gap-3"><div><h2 class="text-2xl font-extrabold">{{ book.title }}</h2><p class="text-[#384c3d]">{{ book.author || '未知作者' }}</p></div><Badge :tone="book.parse_status === 'completed' ? 'green' : book.parse_status === 'failed' ? 'red' : 'amber'">{{ book.parse_status }}</Badge></div><p class="text-[#384c3d]">{{ book.description || '暂无简介' }}</p><dl class="grid gap-3 md:grid-cols-3"><div class="rounded-lg bg-[#edf3e8] p-4"><dt class="text-xs font-bold uppercase text-[#384c3d]">页数</dt><dd class="mt-1 text-2xl font-extrabold">{{ book.page_count || pages.length || 0 }}</dd></div><div class="rounded-lg bg-[#edf3e8] p-4"><dt class="text-xs font-bold uppercase text-[#384c3d]">当前页</dt><dd class="mt-1 text-2xl font-extrabold">{{ book.current_page || 1 }}</dd></div><div class="rounded-lg bg-[#edf3e8] p-4"><dt class="text-xs font-bold uppercase text-[#384c3d]">解析页文本</dt><dd class="mt-1 text-2xl font-extrabold">{{ pages.length }}</dd></div></dl><p v-if="book.parse_error" class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ book.parse_error }}</p></article></section></template>
